apiVersion: v1
kind: Service
metadata:
  labels:
    service: powerapp-web-service
  name: powerapp-web-service
spec:
  type: ClusterIP
  ports:
  - name: "web"
    port: 80
    protocol: TCP
  selector:
    app: powerapp-web
